newaction {
    trigger = "clean",
    description = [[Clean project files generated by Premake5
                   -----
                   Options:
                    -A|--all - Clean both project and build files
                    -b|--build - Clean the entire build
                    -a|--application - Clean Application project
                    -l|--library - Clean Library project
                    -t|--test - Clean Test project
                    -s|--self - Clean all non-external projects]],
    execute = function()

        -- No args
        if (_ARGS[1] == nil) then
            print("Cleaning Generated")
            os.rmdir("./Generated")
            return
        end

        local index = 1;
        while (_ARGS[index] ~= nil) do
            local arg = _ARGS[index]

            if (arg == ("-A" or "--all")) then
                print("Cleaning All")

                os.rmdir("./Generated")
                os.rmdir("./.vscode")
                os.rmdir("./.vs")
                os.rmdir("./.idea")
                os.rmdir("./Build")
            end

            if (arg == ("-b" or "--build")) then
                print("Cleaning Build")

                os.rmdir("./Build")
            end

            if (arg == ("-a" or "--application")) then
                print("Cleaning Application")

                os.rmdir("./Build/obj/Application")
                os.rmdir("./Build/target/Application")
                os.remove("./Generated/Application.vcxproj")
                os.remove("./Generated/Makefile")
            end

            if (arg == ("-l" or "--library")) then
                print("Cleaning Library")

                os.rmdir("./Build/obj/Library")
                os.rmdir("./Build/target/Library")
                os.remove("./Generated/Library.vcxproj")
                os.remove("./Generated/Library.make")
            end

            if (arg == ("-t" or "--test")) then
                print("Cleaning Test")

                os.rmdir("./Build/obj/Test")
                os.rmdir("./Build/target/Test")
                os.remove("./Generated/Test.vcxproj")
                os.remove("./Generated/Test.make")
            end

            if (arg == ("-s" or "--self")) then
                print("Cleaning Self")

                -- Application
                os.rmdir("./Build/obj/Application")
                os.rmdir("./Build/target/Application")
                os.remove("./Generated/Application.vcxproj")
                os.remove("./Generated/Makefile")

                -- Library
                os.rmdir("./Build/obj/Library")
                os.rmdir("./Build/target/Library")
                os.remove("./Generated/Library.vcxproj")
                os.remove("./Generated/Library.make")

                -- Test
                os.rmdir("./Build/obj/Test")
                os.rmdir("./Build/target/Test")
                os.remove("./Generated/Test.vcxproj")
                os.remove("./Generated/Test.make")
            end

            index = index + 1
        end
    end
}

